# Generated by Django 5.0.4 on 2024-05-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('tf', models.IntegerField(verbose_name='tf')),
                ('idf', models.IntegerField(verbose_name='idf')),
            ],
        ),
    ]
